 0  0 SEQ/1                  ""   0          "SDAER"  :proceed (SEQ (POS# 0) (ALT "B" "R") ???)
 1  0 POS#/1                 ""   0          "SDAER"  :proceed (POS# 0)
 0  0 SEQ/1                  ""   0          "SDAER"  :succeed (SEQ . (ALT "B" "R") ???)
 0  0 SEQ/2                  ""   0          "SDAER"  :proceed (SEQ . (ALT "B" "R") (ALT "E" "EA") ??)
 1  0 ALT/1                  ""   0          "SDAER"  :proceed (ALT "B" "R")
 2  1 LIT$/1                 ""   0          "SDAER"  :proceed "B"
 1  1 ALT/1                  ""   0          "SDAER"  :fail    (ALT "B" "R")
 1  1 ALT/2                  ""   0          "SDAER"  :proceed (ALT . "R")
 2  2 LIT$/1                 ""   0          "SDAER"  :proceed "R"
 1  2 ALT/2                  ""   0          "SDAER"  :succeed (ALT ..)
 0  2 SEQ/2                  ""   0          "SDAER"  :succeed (SEQ .. (ALT "E" "EA") ??)
 0  2 SEQ/3                 "R"   1           "SDAE"  :proceed (SEQ .. (ALT "E" "EA") (ALT "D" "DS") ?)
 1  2 ALT/1                 "R"   1           "SDAE"  :proceed (ALT "E" "EA")
 2  3 LIT$/1                "R"   1           "SDAE"  :proceed "E"
 1  3 ALT/1                 "R"   1           "SDAE"  :succeed (ALT . "EA")
 0  3 SEQ/3                 "R"   1           "SDAE"  :succeed (SEQ ... (ALT "D" "DS") ?)
 0  3 SEQ/4                "RE"   2            "SDA"  :proceed (SEQ ... (ALT "D" "DS") (RPOS# 0))
 1  3 ALT/1                "RE"   2            "SDA"  :proceed (ALT "D" "DS")
 2  4 LIT$/1               "RE"   2            "SDA"  :proceed "D"
 1  4 ALT/1                "RE"   2            "SDA"  :fail    (ALT "D" "DS")
 1  4 ALT/2                "RE"   2            "SDA"  :proceed (ALT . "DS")
 2  5 LIT$/1               "RE"   2            "SDA"  :proceed "DS"
 1  5 ALT/2                "RE"   2            "SDA"  :fail    (ALT . "DS")
 1  5 ALT/3                "RE"   2            "SDA"  :proceed (ALT ..)
 1  4 ALT/2                "RE"   2            "SDA"  :recede  (ALT . "DS")
 1  4 ALT/3                "RE"   2            "SDA"  :proceed (ALT ..)
 1  3 ALT/1                "RE"   2            "SDA"  :recede  (ALT "D" "DS")
 1  3 ALT/2                "RE"   2            "SDA"  :proceed (ALT . "DS")
 2  4 LIT$/1               "RE"   2            "SDA"  :proceed "DS"
 1  4 ALT/2                "RE"   2            "SDA"  :fail    (ALT . "DS")
 1  4 ALT/3                "RE"   2            "SDA"  :proceed (ALT ..)
 1  3 ALT/2                "RE"   2            "SDA"  :recede  (ALT . "DS")
 1  3 ALT/3                "RE"   2            "SDA"  :proceed (ALT ..)
 1  2 ALT/1                 "R"   1           "SDAE"  :recede  (ALT "E" "EA")
 1  2 ALT/2                 "R"   1           "SDAE"  :proceed (ALT . "EA")
 2  3 LIT$/1                "R"   1           "SDAE"  :proceed "EA"
 1  3 ALT/2                 "R"   1           "SDAE"  :succeed (ALT ..)
 0  3 SEQ/3                 "R"   1           "SDAE"  :succeed (SEQ ... (ALT "D" "DS") ?)
 0  3 SEQ/4               "REA"   3             "SD"  :proceed (SEQ ... (ALT "D" "DS") (RPOS# 0))
 1  3 ALT/1               "REA"   3             "SD"  :proceed (ALT "D" "DS")
 2  4 LIT$/1              "REA"   3             "SD"  :proceed "D"
 1  4 ALT/1               "REA"   3             "SD"  :succeed (ALT . "DS")
 0  4 SEQ/4               "REA"   3             "SD"  :succeed (SEQ .... (RPOS# 0))
 0  4 SEQ/5              "READ"   4              "S"  :proceed (SEQ .... (RPOS# 0))
 1  4 RPOS#/1            "READ"   4              "S"  :proceed (RPOS# 0)
 0  4 SEQ/5              "READ"   4              "S"  :fail    (SEQ .... (RPOS# 0))
 1  3 ALT/1               "REA"   3             "SD"  :recede  (ALT "D" "DS")
 1  3 ALT/2               "REA"   3             "SD"  :proceed (ALT . "DS")
 2  4 LIT$/1              "REA"   3             "SD"  :proceed "DS"
 1  4 ALT/2               "REA"   3             "SD"  :succeed (ALT ..)
 0  4 SEQ/4               "REA"   3             "SD"  :succeed (SEQ .... (RPOS# 0))
 0  4 SEQ/5             "READS"   5               ""  :proceed (SEQ .... (RPOS# 0))
 1  4 RPOS#/1           "READS"   5               ""  :proceed (RPOS# 0)
 0  4 SEQ/5             "READS"   5               ""  :succeed (SEQ .....)
 0  4 SEQ/6             "READS"   5               ""  :proceed (SEQ .....)
 0  4 /                 "READS"   5               ""  :succeed nil
