static const PATTERN BEARDS_1 = {POS, .n=0};
static const PATTERN BEARDS_5 = {σ, .s="BE"};
static const PATTERN BEARDS_6 = {σ, .s="BEA"};
static const PATTERN BEARDS_7 = {σ, .s="BEAR"};
static const PATTERN BEARDS_4 = {Π, 3, {&BEARDS_5, &BEARDS_6, &BEARDS_7}};
static const PATTERN BEARDS_9 = {σ, .s="DS"};
static const PATTERN BEARDS_10 = {σ, .s="D"};
static const PATTERN BEARDS_8 = {Π, 2, {&BEARDS_9, &BEARDS_10}};
static const PATTERN BEARDS_3 = {Σ, 2, {&BEARDS_4, &BEARDS_8}};
static const PATTERN BEARDS_13 = {σ, .s="RO"};
static const PATTERN BEARDS_14 = {σ, .s="ROO"};
static const PATTERN BEARDS_15 = {σ, .s="ROOS"};
static const PATTERN BEARDS_12 = {Π, 3, {&BEARDS_13, &BEARDS_14, &BEARDS_15}};
static const PATTERN BEARDS_17 = {σ, .s="TS"};
static const PATTERN BEARDS_18 = {σ, .s="T"};
static const PATTERN BEARDS_16 = {Π, 2, {&BEARDS_17, &BEARDS_18}};
static const PATTERN BEARDS_11 = {Σ, 2, {&BEARDS_12, &BEARDS_16}};
static const PATTERN BEARDS_2 = {Π, 2, {&BEARDS_3, &BEARDS_11}};
static const PATTERN BEARDS_19 = {RPOS, .n=0};
static const PATTERN BEARDS_0 = {Σ, 3, {&BEARDS_1, &BEARDS_2, &BEARDS_19}};
