 0  0 SEQ/1                  ""   0          "z*y+x"  :proceed (SEQ (POS# 0) X ?)
 1  0 POS#/1                 ""   0          "z*y+x"  :proceed (POS# 0)
 0  0 SEQ/1                  ""   0          "z*y+x"  :succeed (SEQ . X ?)
 0  0 SEQ/2                  ""   0          "z*y+x"  :proceed (SEQ . X (RPOS# 0))
 1  0 ALT/1                  ""   0          "z*y+x"  :proceed (ALT (SEQ (ALT _ _ _) "+" X) (SEQ (ALT _ _ _) "-" X) ?????)
 2  1 SEQ/1                  ""   0          "z*y+x"  :proceed (SEQ (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")) "+" ?)
 3  1 ALT/1                  ""   0          "z*y+x"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 4  2 ANY$/1                 ""   0          "z*y+x"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 3  2 ALT/1                  ""   0          "z*y+x"  :succeed (ALT . (SPAN$ "0123456789") ?)
 2  2 SEQ/1                  ""   0          "z*y+x"  :succeed (SEQ . "+" ?)
 2  2 SEQ/2                 "x"   1           "z*y+"  :proceed (SEQ . "+" X)
 3  2 LIT$/1                "x"   1           "z*y+"  :proceed "+"
 2  2 SEQ/2                 "x"   1           "z*y+"  :succeed (SEQ .. X)
 2  2 SEQ/3                "x+"   2            "z*y"  :proceed (SEQ .. X)
 3  2 X/1                  "x+"   2            "z*y"  :proceed X
 3  2 ALT/1                "x+"   2            "z*y"  :proceed (ALT (SEQ (ALT _ _ _) "+" X) (SEQ (ALT _ _ _) "-" X) ?????)
 4  3 SEQ/1                "x+"   2            "z*y"  :proceed (SEQ (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")) "+" ?)
 5  3 ALT/1                "x+"   2            "z*y"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 6  4 ANY$/1               "x+"   2            "z*y"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 5  4 ALT/1                "x+"   2            "z*y"  :succeed (ALT . (SPAN$ "0123456789") ?)
 4  4 SEQ/1                "x+"   2            "z*y"  :succeed (SEQ . "+" ?)
 4  4 SEQ/2               "x+y"   3             "z*"  :proceed (SEQ . "+" X)
 5  4 LIT$/1              "x+y"   3             "z*"  :proceed "+"
 4  4 SEQ/2               "x+y"   3             "z*"  :fail    (SEQ . "+" X)
 5  3 ALT/1                "x+"   2            "z*y"  :recede  (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 5  3 ALT/2                "x+"   2            "z*y"  :proceed (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 6  4 SPAN$/1              "x+"   2            "z*y"  :proceed (SPAN$ "0123456789")
 5  4 ALT/2                "x+"   2            "z*y"  :fail    (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 5  4 ALT/3                "x+"   2            "z*y"  :proceed (ALT .. (SEQ "(" X ")"))
 6  5 SEQ/1                "x+"   2            "z*y"  :proceed (SEQ "(" X ?)
 7  5 LIT$/1               "x+"   2            "z*y"  :proceed "("
 6  5 SEQ/1                "x+"   2            "z*y"  :fail    (SEQ "(" X ?)
 5  4 ALT/3                "x+"   2            "z*y"  :recede  (ALT .. (SEQ "(" X ")"))
 5  4 ALT/4                "x+"   2            "z*y"  :proceed (ALT ...)
 5  3 ALT/2                "x+"   2            "z*y"  :recede  (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 5  3 ALT/3                "x+"   2            "z*y"  :proceed (ALT .. (SEQ "(" X ")"))
 6  4 SEQ/1                "x+"   2            "z*y"  :proceed (SEQ "(" X ?)
 7  4 LIT$/1               "x+"   2            "z*y"  :proceed "("
 6  4 SEQ/1                "x+"   2            "z*y"  :fail    (SEQ "(" X ?)
 5  3 ALT/3                "x+"   2            "z*y"  :recede  (ALT .. (SEQ "(" X ")"))
 5  3 ALT/4                "x+"   2            "z*y"  :proceed (ALT ...)
 3  2 ALT/1                "x+"   2            "z*y"  :recede  (ALT (SEQ (ALT _ _ _) "+" X) (SEQ (ALT _ _ _) "-" X) ?????)
 3  2 ALT/2                "x+"   2            "z*y"  :proceed (ALT . (SEQ (ALT _ _ _) "-" X) (SEQ (ALT _ _ _) "*" X) ????)
 4  3 SEQ/1                "x+"   2            "z*y"  :proceed (SEQ (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")) "-" ?)
 5  3 ALT/1                "x+"   2            "z*y"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 6  4 ANY$/1               "x+"   2            "z*y"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 5  4 ALT/1                "x+"   2            "z*y"  :succeed (ALT . (SPAN$ "0123456789") ?)
 4  4 SEQ/1                "x+"   2            "z*y"  :succeed (SEQ . "-" ?)
 4  4 SEQ/2               "x+y"   3             "z*"  :proceed (SEQ . "-" X)
 5  4 LIT$/1              "x+y"   3             "z*"  :proceed "-"
 4  4 SEQ/2               "x+y"   3             "z*"  :fail    (SEQ . "-" X)
 5  3 ALT/1                "x+"   2            "z*y"  :recede  (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 5  3 ALT/2                "x+"   2            "z*y"  :proceed (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 6  4 SPAN$/1              "x+"   2            "z*y"  :proceed (SPAN$ "0123456789")
 5  4 ALT/2                "x+"   2            "z*y"  :fail    (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 5  4 ALT/3                "x+"   2            "z*y"  :proceed (ALT .. (SEQ "(" X ")"))
 6  5 SEQ/1                "x+"   2            "z*y"  :proceed (SEQ "(" X ?)
 7  5 LIT$/1               "x+"   2            "z*y"  :proceed "("
 6  5 SEQ/1                "x+"   2            "z*y"  :fail    (SEQ "(" X ?)
 5  4 ALT/3                "x+"   2            "z*y"  :recede  (ALT .. (SEQ "(" X ")"))
 5  4 ALT/4                "x+"   2            "z*y"  :proceed (ALT ...)
 5  3 ALT/2                "x+"   2            "z*y"  :recede  (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 5  3 ALT/3                "x+"   2            "z*y"  :proceed (ALT .. (SEQ "(" X ")"))
 6  4 SEQ/1                "x+"   2            "z*y"  :proceed (SEQ "(" X ?)
 7  4 LIT$/1               "x+"   2            "z*y"  :proceed "("
 6  4 SEQ/1                "x+"   2            "z*y"  :fail    (SEQ "(" X ?)
 5  3 ALT/3                "x+"   2            "z*y"  :recede  (ALT .. (SEQ "(" X ")"))
 5  3 ALT/4                "x+"   2            "z*y"  :proceed (ALT ...)
 3  2 ALT/2                "x+"   2            "z*y"  :recede  (ALT . (SEQ (ALT _ _ _) "-" X) (SEQ (ALT _ _ _) "*" X) ????)
 3  2 ALT/3                "x+"   2            "z*y"  :proceed (ALT .. (SEQ (ALT _ _ _) "*" X) (SEQ (ALT _ _ _) "/" X) ???)
 4  3 SEQ/1                "x+"   2            "z*y"  :proceed (SEQ (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")) "*" ?)
 5  3 ALT/1                "x+"   2            "z*y"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 6  4 ANY$/1               "x+"   2            "z*y"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 5  4 ALT/1                "x+"   2            "z*y"  :succeed (ALT . (SPAN$ "0123456789") ?)
 4  4 SEQ/1                "x+"   2            "z*y"  :succeed (SEQ . "*" ?)
 4  4 SEQ/2               "x+y"   3             "z*"  :proceed (SEQ . "*" X)
 5  4 LIT$/1              "x+y"   3             "z*"  :proceed "*"
 4  4 SEQ/2               "x+y"   3             "z*"  :succeed (SEQ .. X)
 4  4 SEQ/3              "x+y*"   4              "z"  :proceed (SEQ .. X)
 5  4 X/1                "x+y*"   4              "z"  :proceed X
 5  4 ALT/1              "x+y*"   4              "z"  :proceed (ALT (SEQ (ALT _ _ _) "+" X) (SEQ (ALT _ _ _) "-" X) ?????)
 6  5 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")) "+" ?)
 7  5 ALT/1              "x+y*"   4              "z"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 8  6 ANY$/1             "x+y*"   4              "z"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 7  6 ALT/1              "x+y*"   4              "z"  :succeed (ALT . (SPAN$ "0123456789") ?)
 6  6 SEQ/1              "x+y*"   4              "z"  :succeed (SEQ . "+" ?)
 6  6 SEQ/2             "x+y*z"   5               ""  :proceed (SEQ . "+" X)
 7  6 LIT$/1            "x+y*z"   5               ""  :proceed "+"
 6  6 SEQ/2             "x+y*z"   5               ""  :fail    (SEQ . "+" X)
 7  5 ALT/1              "x+y*"   4              "z"  :recede  (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 7  5 ALT/2              "x+y*"   4              "z"  :proceed (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 8  6 SPAN$/1            "x+y*"   4              "z"  :proceed (SPAN$ "0123456789")
 7  6 ALT/2              "x+y*"   4              "z"  :fail    (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 7  6 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ "(" X ")"))
 8  7 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "(" X ?)
 9  7 LIT$/1             "x+y*"   4              "z"  :proceed "("
 8  7 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "(" X ?)
 7  6 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ "(" X ")"))
 7  6 ALT/4              "x+y*"   4              "z"  :proceed (ALT ...)
 7  5 ALT/2              "x+y*"   4              "z"  :recede  (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 7  5 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ "(" X ")"))
 8  6 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "(" X ?)
 9  6 LIT$/1             "x+y*"   4              "z"  :proceed "("
 8  6 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "(" X ?)
 7  5 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ "(" X ")"))
 7  5 ALT/4              "x+y*"   4              "z"  :proceed (ALT ...)
 5  4 ALT/1              "x+y*"   4              "z"  :recede  (ALT (SEQ (ALT _ _ _) "+" X) (SEQ (ALT _ _ _) "-" X) ?????)
 5  4 ALT/2              "x+y*"   4              "z"  :proceed (ALT . (SEQ (ALT _ _ _) "-" X) (SEQ (ALT _ _ _) "*" X) ????)
 6  5 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")) "-" ?)
 7  5 ALT/1              "x+y*"   4              "z"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 8  6 ANY$/1             "x+y*"   4              "z"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 7  6 ALT/1              "x+y*"   4              "z"  :succeed (ALT . (SPAN$ "0123456789") ?)
 6  6 SEQ/1              "x+y*"   4              "z"  :succeed (SEQ . "-" ?)
 6  6 SEQ/2             "x+y*z"   5               ""  :proceed (SEQ . "-" X)
 7  6 LIT$/1            "x+y*z"   5               ""  :proceed "-"
 6  6 SEQ/2             "x+y*z"   5               ""  :fail    (SEQ . "-" X)
 7  5 ALT/1              "x+y*"   4              "z"  :recede  (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 7  5 ALT/2              "x+y*"   4              "z"  :proceed (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 8  6 SPAN$/1            "x+y*"   4              "z"  :proceed (SPAN$ "0123456789")
 7  6 ALT/2              "x+y*"   4              "z"  :fail    (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 7  6 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ "(" X ")"))
 8  7 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "(" X ?)
 9  7 LIT$/1             "x+y*"   4              "z"  :proceed "("
 8  7 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "(" X ?)
 7  6 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ "(" X ")"))
 7  6 ALT/4              "x+y*"   4              "z"  :proceed (ALT ...)
 7  5 ALT/2              "x+y*"   4              "z"  :recede  (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 7  5 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ "(" X ")"))
 8  6 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "(" X ?)
 9  6 LIT$/1             "x+y*"   4              "z"  :proceed "("
 8  6 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "(" X ?)
 7  5 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ "(" X ")"))
 7  5 ALT/4              "x+y*"   4              "z"  :proceed (ALT ...)
 5  4 ALT/2              "x+y*"   4              "z"  :recede  (ALT . (SEQ (ALT _ _ _) "-" X) (SEQ (ALT _ _ _) "*" X) ????)
 5  4 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ (ALT _ _ _) "*" X) (SEQ (ALT _ _ _) "/" X) ???)
 6  5 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")) "*" ?)
 7  5 ALT/1              "x+y*"   4              "z"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 8  6 ANY$/1             "x+y*"   4              "z"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 7  6 ALT/1              "x+y*"   4              "z"  :succeed (ALT . (SPAN$ "0123456789") ?)
 6  6 SEQ/1              "x+y*"   4              "z"  :succeed (SEQ . "*" ?)
 6  6 SEQ/2             "x+y*z"   5               ""  :proceed (SEQ . "*" X)
 7  6 LIT$/1            "x+y*z"   5               ""  :proceed "*"
 6  6 SEQ/2             "x+y*z"   5               ""  :fail    (SEQ . "*" X)
 7  5 ALT/1              "x+y*"   4              "z"  :recede  (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 7  5 ALT/2              "x+y*"   4              "z"  :proceed (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 8  6 SPAN$/1            "x+y*"   4              "z"  :proceed (SPAN$ "0123456789")
 7  6 ALT/2              "x+y*"   4              "z"  :fail    (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 7  6 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ "(" X ")"))
 8  7 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "(" X ?)
 9  7 LIT$/1             "x+y*"   4              "z"  :proceed "("
 8  7 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "(" X ?)
 7  6 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ "(" X ")"))
 7  6 ALT/4              "x+y*"   4              "z"  :proceed (ALT ...)
 7  5 ALT/2              "x+y*"   4              "z"  :recede  (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 7  5 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ "(" X ")"))
 8  6 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "(" X ?)
 9  6 LIT$/1             "x+y*"   4              "z"  :proceed "("
 8  6 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "(" X ?)
 7  5 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ "(" X ")"))
 7  5 ALT/4              "x+y*"   4              "z"  :proceed (ALT ...)
 5  4 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ (ALT _ _ _) "*" X) (SEQ (ALT _ _ _) "/" X) ???)
 5  4 ALT/4              "x+y*"   4              "z"  :proceed (ALT ... (SEQ (ALT _ _ _) "/" X) (SEQ "+" X) ??)
 6  5 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")) "/" ?)
 7  5 ALT/1              "x+y*"   4              "z"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 8  6 ANY$/1             "x+y*"   4              "z"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 7  6 ALT/1              "x+y*"   4              "z"  :succeed (ALT . (SPAN$ "0123456789") ?)
 6  6 SEQ/1              "x+y*"   4              "z"  :succeed (SEQ . "/" ?)
 6  6 SEQ/2             "x+y*z"   5               ""  :proceed (SEQ . "/" X)
 7  6 LIT$/1            "x+y*z"   5               ""  :proceed "/"
 6  6 SEQ/2             "x+y*z"   5               ""  :fail    (SEQ . "/" X)
 7  5 ALT/1              "x+y*"   4              "z"  :recede  (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 7  5 ALT/2              "x+y*"   4              "z"  :proceed (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 8  6 SPAN$/1            "x+y*"   4              "z"  :proceed (SPAN$ "0123456789")
 7  6 ALT/2              "x+y*"   4              "z"  :fail    (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 7  6 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ "(" X ")"))
 8  7 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "(" X ?)
 9  7 LIT$/1             "x+y*"   4              "z"  :proceed "("
 8  7 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "(" X ?)
 7  6 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ "(" X ")"))
 7  6 ALT/4              "x+y*"   4              "z"  :proceed (ALT ...)
 7  5 ALT/2              "x+y*"   4              "z"  :recede  (ALT . (SPAN$ "0123456789") (SEQ "(" X ")"))
 7  5 ALT/3              "x+y*"   4              "z"  :proceed (ALT .. (SEQ "(" X ")"))
 8  6 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "(" X ?)
 9  6 LIT$/1             "x+y*"   4              "z"  :proceed "("
 8  6 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "(" X ?)
 7  5 ALT/3              "x+y*"   4              "z"  :recede  (ALT .. (SEQ "(" X ")"))
 7  5 ALT/4              "x+y*"   4              "z"  :proceed (ALT ...)
 5  4 ALT/4              "x+y*"   4              "z"  :recede  (ALT ... (SEQ (ALT _ _ _) "/" X) (SEQ "+" X) ??)
 5  4 ALT/5              "x+y*"   4              "z"  :proceed (ALT .... (SEQ "+" X) (SEQ "-" X) ?)
 6  5 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "+" X)
 7  5 LIT$/1             "x+y*"   4              "z"  :proceed "+"
 6  5 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "+" X)
 5  4 ALT/5              "x+y*"   4              "z"  :recede  (ALT .... (SEQ "+" X) (SEQ "-" X) ?)
 5  4 ALT/6              "x+y*"   4              "z"  :proceed (ALT ..... (SEQ "-" X) (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")))
 6  5 SEQ/1              "x+y*"   4              "z"  :proceed (SEQ "-" X)
 7  5 LIT$/1             "x+y*"   4              "z"  :proceed "-"
 6  5 SEQ/1              "x+y*"   4              "z"  :fail    (SEQ "-" X)
 5  4 ALT/6              "x+y*"   4              "z"  :recede  (ALT ..... (SEQ "-" X) (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")))
 5  4 ALT/7              "x+y*"   4              "z"  :proceed (ALT ...... (ALT (ANY$ _) (SPAN$ _) (SEQ "(" X ")")))
 6  5 ALT/1              "x+y*"   4              "z"  :proceed (ALT (ANY$ "abcdefghijklmnopqrstuvwxyz") (SPAN$ "0123456789") ?)
 7  6 ANY$/1             "x+y*"   4              "z"  :proceed (ANY$ "abcdefghijklmnopqrstuvwxyz")
 6  6 ALT/1              "x+y*"   4              "z"  :succeed (ALT . (SPAN$ "0123456789") ?)
 5  6 ALT/7              "x+y*"   4              "z"  :succeed (ALT .......)
 4  6 SEQ/3              "x+y*"   4              "z"  :succeed (SEQ ...)
 4  6 SEQ/4             "x+y*z"   5               ""  :proceed (SEQ ...)
 3  6 ALT/3             "x+y*z"   5               ""  :succeed (ALT ... (SEQ (ALT _ _ _) "/" X) ???)
 2  6 SEQ/3             "x+y*z"   5               ""  :succeed (SEQ ...)
 2  6 SEQ/4             "x+y*z"   5               ""  :proceed (SEQ ...)
 1  6 ALT/1             "x+y*z"   5               ""  :succeed (ALT . (SEQ (ALT _ _ _) "-" X) ?????)
 0  6 SEQ/2             "x+y*z"   5               ""  :succeed (SEQ .. (RPOS# 0))
 0  6 SEQ/3             "x+y*z"   5               ""  :proceed (SEQ .. (RPOS# 0))
 1  6 RPOS#/1           "x+y*z"   5               ""  :proceed (RPOS# 0)
 0  6 SEQ/3             "x+y*z"   5               ""  :succeed (SEQ ...)
 0  6 SEQ/4             "x+y*z"   5               ""  :proceed (SEQ ...)
 0  6 /                 "x+y*z"   5               ""  :succeed nil

