static const PATTERN C_1  = {POS, .n=0};
static const PATTERN C_2  = {λ, .command="S = []"};
static const PATTERN C_8  = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_7  = {Δ, .s="N", &C_8};
static const PATTERN C_9  = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN C_6  = {Σ, 2, {&C_7, &C_9}};
static const PATTERN C_12 = {SPAN, .chars="0123456789"};
static const PATTERN C_11 = {Δ, .s="N", &C_12};
static const PATTERN C_13 = {λ, .command="S.append(int(N))"};
static const PATTERN C_10 = {Σ, 2, {&C_11, &C_13}};
static const PATTERN C_15 = {σ, .s="("};
static const PATTERN C_16 = {ζ, .N="X"};
static const PATTERN C_17 = {σ, .s=")"};
static const PATTERN C_14 = {Σ, 3, {&C_15, &C_16, &C_17}};
static const PATTERN C_5  = {Π, 3, {&C_6, &C_10, &C_14}};
static const PATTERN C_18 = {σ, .s="+"};
static const PATTERN C_19 = {ζ, .N="X"};
static const PATTERN C_20 = {λ, .command="S.append(S.pop() + S.pop())"};
static const PATTERN C_4  = {Σ, 4, {&C_5, &C_18, &C_19, &C_20}};
static const PATTERN C_25 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_24 = {Δ, .s="N", &C_25};
static const PATTERN C_26 = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN C_23 = {Σ, 2, {&C_24, &C_26}};
static const PATTERN C_29 = {SPAN, .chars="0123456789"};
static const PATTERN C_28 = {Δ, .s="N", &C_29};
static const PATTERN C_30 = {λ, .command="S.append(int(N))"};
static const PATTERN C_27 = {Σ, 2, {&C_28, &C_30}};
static const PATTERN C_32 = {σ, .s="("};
static const PATTERN C_33 = {ζ, .N="X"};
static const PATTERN C_34 = {σ, .s=")"};
static const PATTERN C_31 = {Σ, 3, {&C_32, &C_33, &C_34}};
static const PATTERN C_22 = {Π, 3, {&C_23, &C_27, &C_31}};
static const PATTERN C_35 = {σ, .s="-"};
static const PATTERN C_36 = {ζ, .N="X"};
static const PATTERN C_37 = {λ, .command="S.append(S.pop() - S.pop())"};
static const PATTERN C_21 = {Σ, 4, {&C_22, &C_35, &C_36, &C_37}};
static const PATTERN C_42 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_41 = {Δ, .s="N", &C_42};
static const PATTERN C_43 = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN C_40 = {Σ, 2, {&C_41, &C_43}};
static const PATTERN C_46 = {SPAN, .chars="0123456789"};
static const PATTERN C_45 = {Δ, .s="N", &C_46};
static const PATTERN C_47 = {λ, .command="S.append(int(N))"};
static const PATTERN C_44 = {Σ, 2, {&C_45, &C_47}};
static const PATTERN C_49 = {σ, .s="("};
static const PATTERN C_50 = {ζ, .N="X"};
static const PATTERN C_51 = {σ, .s=")"};
static const PATTERN C_48 = {Σ, 3, {&C_49, &C_50, &C_51}};
static const PATTERN C_39 = {Π, 3, {&C_40, &C_44, &C_48}};
static const PATTERN C_52 = {σ, .s="*"};
static const PATTERN C_53 = {ζ, .N="X"};
static const PATTERN C_54 = {λ, .command="S.append(S.pop() * S.pop())"};
static const PATTERN C_38 = {Σ, 4, {&C_39, &C_52, &C_53, &C_54}};
static const PATTERN C_59 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_58 = {Δ, .s="N", &C_59};
static const PATTERN C_60 = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN C_57 = {Σ, 2, {&C_58, &C_60}};
static const PATTERN C_63 = {SPAN, .chars="0123456789"};
static const PATTERN C_62 = {Δ, .s="N", &C_63};
static const PATTERN C_64 = {λ, .command="S.append(int(N))"};
static const PATTERN C_61 = {Σ, 2, {&C_62, &C_64}};
static const PATTERN C_66 = {σ, .s="("};
static const PATTERN C_67 = {ζ, .N="X"};
static const PATTERN C_68 = {σ, .s=")"};
static const PATTERN C_65 = {Σ, 3, {&C_66, &C_67, &C_68}};
static const PATTERN C_56 = {Π, 3, {&C_57, &C_61, &C_65}};
static const PATTERN C_69 = {σ, .s="/"};
static const PATTERN C_70 = {ζ, .N="X"};
static const PATTERN C_71 = {λ, .command="S.append(S.pop() // S.pop())"};
static const PATTERN C_55 = {Σ, 4, {&C_56, &C_69, &C_70, &C_71}};
static const PATTERN C_73 = {σ, .s="+"};
static const PATTERN C_74 = {ζ, .N="X"};
static const PATTERN C_72 = {Σ, 2, {&C_73, &C_74}};
static const PATTERN C_76 = {σ, .s="-"};
static const PATTERN C_77 = {ζ, .N="X"};
static const PATTERN C_78 = {λ, .command="S.append(-S.pop())"};
static const PATTERN C_75 = {Σ, 3, {&C_76, &C_77, &C_78}};
static const PATTERN C_82 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_81 = {Δ, .s="N", &C_82};
static const PATTERN C_83 = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN C_80 = {Σ, 2, {&C_81, &C_83}};
static const PATTERN C_86 = {SPAN, .chars="0123456789"};
static const PATTERN C_85 = {Δ, .s="N", &C_86};
static const PATTERN C_87 = {λ, .command="S.append(int(N))"};
static const PATTERN C_84 = {Σ, 2, {&C_85, &C_87}};
static const PATTERN C_89 = {σ, .s="("};
static const PATTERN C_90 = {ζ, .N="X"};
static const PATTERN C_91 = {σ, .s=")"};
static const PATTERN C_88 = {Σ, 3, {&C_89, &C_90, &C_91}};
static const PATTERN C_79 = {Π, 3, {&C_80, &C_84, &C_88}};
static const PATTERN C_3  = {Π, 7, {&C_4, &C_21, &C_38, &C_55, &C_72, &C_75, &C_79}};
static const PATTERN C_92 = {λ, .command="print(S.pop())"};
static const PATTERN C_93 = {RPOS, .n=0};
static const PATTERN C_0  = {Σ, 5, {&C_1, &C_2, &C_3, &C_92, &C_93}};
