static const PATTERN C_1  = {POS, .n=0};
static const PATTERN C_6  = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_10 = {SPAN, .chars="0123456789"};
static const PATTERN C_15 = {σ, .s="("};
static const PATTERN C_16 = {ζ, .N="X"};
static const PATTERN C_17 = {σ, .s=")"};
static const PATTERN C_14 = {Σ, 3, {&C_15, &C_16, &C_17}};
static const PATTERN C_5  = {Π, 3, {&C_6, &C_10, &C_14}};
static const PATTERN C_18 = {σ, .s="+"};
static const PATTERN C_19 = {ζ, .N="X"};
static const PATTERN C_4  = {Σ, 3, {&C_5, &C_18, &C_19}};
static const PATTERN C_23 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_27 = {SPAN, .chars="0123456789"};
static const PATTERN C_32 = {σ, .s="("};
static const PATTERN C_33 = {ζ, .N="X"};
static const PATTERN C_34 = {σ, .s=")"};
static const PATTERN C_31 = {Σ, 3, {&C_32, &C_33, &C_34}};
static const PATTERN C_22 = {Π, 3, {&C_23, &C_27, &C_31}};
static const PATTERN C_35 = {σ, .s="-"};
static const PATTERN C_36 = {ζ, .N="X"};
static const PATTERN C_21 = {Σ, 3, {&C_22, &C_35, &C_36}};
static const PATTERN C_40 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_44 = {SPAN, .chars="0123456789"};
static const PATTERN C_49 = {σ, .s="("};
static const PATTERN C_50 = {ζ, .N="X"};
static const PATTERN C_51 = {σ, .s=")"};
static const PATTERN C_48 = {Σ, 3, {&C_49, &C_50, &C_51}};
static const PATTERN C_39 = {Π, 3, {&C_40, &C_44, &C_48}};
static const PATTERN C_52 = {σ, .s="*"};
static const PATTERN C_53 = {ζ, .N="X"};
static const PATTERN C_38 = {Σ, 3, {&C_39, &C_52, &C_53}};
static const PATTERN C_57 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_61 = {SPAN, .chars="0123456789"};
static const PATTERN C_66 = {σ, .s="("};
static const PATTERN C_67 = {ζ, .N="X"};
static const PATTERN C_68 = {σ, .s=")"};
static const PATTERN C_65 = {Σ, 3, {&C_66, &C_67, &C_68}};
static const PATTERN C_56 = {Π, 3, {&C_57, &C_61, &C_65}};
static const PATTERN C_69 = {σ, .s="/"};
static const PATTERN C_70 = {ζ, .N="X"};
static const PATTERN C_55 = {Σ, 3, {&C_56, &C_69, &C_70}};
static const PATTERN C_73 = {σ, .s="+"};
static const PATTERN C_74 = {ζ, .N="X"};
static const PATTERN C_72 = {Σ, 2, {&C_73, &C_74}};
static const PATTERN C_76 = {σ, .s="-"};
static const PATTERN C_77 = {ζ, .N="X"};
static const PATTERN C_75 = {Σ, 2, {&C_76, &C_77}};
static const PATTERN C_80 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN C_84 = {SPAN, .chars="0123456789"};
static const PATTERN C_89 = {σ, .s="("};
static const PATTERN C_90 = {ζ, .N="X"};
static const PATTERN C_91 = {σ, .s=")"};
static const PATTERN C_88 = {Σ, 3, {&C_89, &C_90, &C_91}};
static const PATTERN C_79 = {Π, 3, {&C_80, &C_84, &C_88}};
static const PATTERN C_3  = {Π, 7, {&C_4, &C_21, &C_38, &C_55, &C_72, &C_75, &C_79}};
static const PATTERN C_93 = {RPOS, .n=0};
static const PATTERN C_0  = {Σ, 3, {&C_1, &C_3, &C_93}};
