static const PATTERN CALC_1  = {POS, .n=0};
static const PATTERN CALC_2  = {λ, .command="S = []"};
static const PATTERN CALC_8  = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN CALC_7  = {Δ, .s="N", &CALC_8};
static const PATTERN CALC_9  = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN CALC_6  = {Σ, 2, {&CALC_7, &CALC_9}};
static const PATTERN CALC_12 = {SPAN, .chars="0123456789"};
static const PATTERN CALC_11 = {Δ, .s="N", &CALC_12};
static const PATTERN CALC_13 = {λ, .command="S.append(int(N))"};
static const PATTERN CALC_10 = {Σ, 2, {&CALC_11, &CALC_13}};
static const PATTERN CALC_15 = {σ, .s="("};
static const PATTERN CALC_16 = {ζ, .N="EXPR"};
static const PATTERN CALC_17 = {σ, .s=")"};
static const PATTERN CALC_14 = {Σ, 3, {&CALC_15, &CALC_16, &CALC_17}};
static const PATTERN CALC_5  = {Π, 3, {&CALC_6, &CALC_10, &CALC_14}};
static const PATTERN CALC_18 = {σ, .s="+"};
static const PATTERN CALC_19 = {ζ, .N="EXPR"};
static const PATTERN CALC_20 = {λ, .command="S.append(S.pop() + S.pop())"};
static const PATTERN CALC_4  = {Σ, 4, {&CALC_5, &CALC_18, &CALC_19, &CALC_20}};
static const PATTERN CALC_25 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN CALC_24 = {Δ, .s="N", &CALC_25};
static const PATTERN CALC_26 = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN CALC_23 = {Σ, 2, {&CALC_24, &CALC_26}};
static const PATTERN CALC_29 = {SPAN, .chars="0123456789"};
static const PATTERN CALC_28 = {Δ, .s="N", &CALC_29};
static const PATTERN CALC_30 = {λ, .command="S.append(int(N))"};
static const PATTERN CALC_27 = {Σ, 2, {&CALC_28, &CALC_30}};
static const PATTERN CALC_32 = {σ, .s="("};
static const PATTERN CALC_33 = {ζ, .N="EXPR"};
static const PATTERN CALC_34 = {σ, .s=")"};
static const PATTERN CALC_31 = {Σ, 3, {&CALC_32, &CALC_33, &CALC_34}};
static const PATTERN CALC_22 = {Π, 3, {&CALC_23, &CALC_27, &CALC_31}};
static const PATTERN CALC_35 = {σ, .s="-"};
static const PATTERN CALC_36 = {ζ, .N="EXPR"};
static const PATTERN CALC_37 = {λ, .command="S.append(S.pop() - S.pop())"};
static const PATTERN CALC_21 = {Σ, 4, {&CALC_22, &CALC_35, &CALC_36, &CALC_37}};
static const PATTERN CALC_42 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN CALC_41 = {Δ, .s="N", &CALC_42};
static const PATTERN CALC_43 = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN CALC_40 = {Σ, 2, {&CALC_41, &CALC_43}};
static const PATTERN CALC_46 = {SPAN, .chars="0123456789"};
static const PATTERN CALC_45 = {Δ, .s="N", &CALC_46};
static const PATTERN CALC_47 = {λ, .command="S.append(int(N))"};
static const PATTERN CALC_44 = {Σ, 2, {&CALC_45, &CALC_47}};
static const PATTERN CALC_49 = {σ, .s="("};
static const PATTERN CALC_50 = {ζ, .N="EXPR"};
static const PATTERN CALC_51 = {σ, .s=")"};
static const PATTERN CALC_48 = {Σ, 3, {&CALC_49, &CALC_50, &CALC_51}};
static const PATTERN CALC_39 = {Π, 3, {&CALC_40, &CALC_44, &CALC_48}};
static const PATTERN CALC_52 = {σ, .s="*"};
static const PATTERN CALC_53 = {ζ, .N="EXPR"};
static const PATTERN CALC_54 = {λ, .command="S.append(S.pop() * S.pop())"};
static const PATTERN CALC_38 = {Σ, 4, {&CALC_39, &CALC_52, &CALC_53, &CALC_54}};
static const PATTERN CALC_59 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN CALC_58 = {Δ, .s="N", &CALC_59};
static const PATTERN CALC_60 = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN CALC_57 = {Σ, 2, {&CALC_58, &CALC_60}};
static const PATTERN CALC_63 = {SPAN, .chars="0123456789"};
static const PATTERN CALC_62 = {Δ, .s="N", &CALC_63};
static const PATTERN CALC_64 = {λ, .command="S.append(int(N))"};
static const PATTERN CALC_61 = {Σ, 2, {&CALC_62, &CALC_64}};
static const PATTERN CALC_66 = {σ, .s="("};
static const PATTERN CALC_67 = {ζ, .N="EXPR"};
static const PATTERN CALC_68 = {σ, .s=")"};
static const PATTERN CALC_65 = {Σ, 3, {&CALC_66, &CALC_67, &CALC_68}};
static const PATTERN CALC_56 = {Π, 3, {&CALC_57, &CALC_61, &CALC_65}};
static const PATTERN CALC_69 = {σ, .s="/"};
static const PATTERN CALC_70 = {ζ, .N="EXPR"};
static const PATTERN CALC_71 = {λ, .command="S.append(S.pop() // S.pop())"};
static const PATTERN CALC_55 = {Σ, 4, {&CALC_56, &CALC_69, &CALC_70, &CALC_71}};
static const PATTERN CALC_73 = {σ, .s="+"};
static const PATTERN CALC_74 = {ζ, .N="EXPR"};
static const PATTERN CALC_72 = {Σ, 2, {&CALC_73, &CALC_74}};
static const PATTERN CALC_76 = {σ, .s="-"};
static const PATTERN CALC_77 = {ζ, .N="EXPR"};
static const PATTERN CALC_78 = {λ, .command="S.append(-S.pop())"};
static const PATTERN CALC_75 = {Σ, 3, {&CALC_76, &CALC_77, &CALC_78}};
static const PATTERN CALC_82 = {ANY, .chars="abcdefghijklmnopqrstuvwxyz"};
static const PATTERN CALC_81 = {Δ, .s="N", &CALC_82};
static const PATTERN CALC_83 = {λ, .command="S.append(int(globals()[N]))"};
static const PATTERN CALC_80 = {Σ, 2, {&CALC_81, &CALC_83}};
static const PATTERN CALC_86 = {SPAN, .chars="0123456789"};
static const PATTERN CALC_85 = {Δ, .s="N", &CALC_86};
static const PATTERN CALC_87 = {λ, .command="S.append(int(N))"};
static const PATTERN CALC_84 = {Σ, 2, {&CALC_85, &CALC_87}};
static const PATTERN CALC_89 = {σ, .s="("};
static const PATTERN CALC_90 = {ζ, .N="EXPR"};
static const PATTERN CALC_91 = {σ, .s=")"};
static const PATTERN CALC_88 = {Σ, 3, {&CALC_89, &CALC_90, &CALC_91}};
static const PATTERN CALC_79 = {Π, 3, {&CALC_80, &CALC_84, &CALC_88}};
static const PATTERN CALC_3  = {Π, 7, {&CALC_4, &CALC_21, &CALC_38, &CALC_55, &CALC_72, &CALC_75, &CALC_79}};
static const PATTERN CALC_92 = {λ, .command="print(S.pop())"};
static const PATTERN CALC_93 = {RPOS, .n=0};
static const PATTERN CALC_0  = {Σ, 5, {&CALC_1, &CALC_2, &CALC_3, &CALC_92, &CALC_93}};
