static PATTERN RE_1 =  {POS, .n=0};
static PATTERN RE_3 =  {nPush};
static PATTERN RE_5 =  {nPush};
static PATTERN RE_10 = {σ, .s="."};
static PATTERN RE_11 = {Shift, .t=".", .v=NULL};
static PATTERN RE_9 =  {Σ, 2, {&RE_10, &RE_11}};
static PATTERN RE_13 = {σ, .s="\\"};
static PATTERN RE_15 = {ANY, .chars=".\\(|*+?)"};
static PATTERN RE_14 = {Δ, .s="tx", &RE_15};
static PATTERN RE_16 = {Shift, .t="σ", .v="tx"};
static PATTERN RE_12 = {Σ, 3, {&RE_13, &RE_14, &RE_16}};
static PATTERN RE_19 = {ANY, .chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"};
static PATTERN RE_18 = {Δ, .s="tx", &RE_19};
static PATTERN RE_20 = {Shift, .t="σ", .v="tx"};
static PATTERN RE_17 = {Σ, 2, {&RE_18, &RE_20}};
static PATTERN RE_22 = {σ, .s="("};
static PATTERN RE_23 = {ζ, .N="RE_Expression"};
static PATTERN RE_24 = {σ, .s=")"};
static PATTERN RE_21 = {Σ, 3, {&RE_22, &RE_23, &RE_24}};
static PATTERN RE_8 =  {Π, 4, {&RE_9, &RE_12, &RE_17, &RE_21}};
static PATTERN RE_29 = {σ, .s="*"};
static PATTERN RE_30 = {Shift, .t="*", .v=NULL};
static PATTERN RE_28 = {Σ, 2, {&RE_29, &RE_30}};
static PATTERN RE_32 = {σ, .s="+"};
static PATTERN RE_33 = {Shift, .t="+", .v=NULL};
static PATTERN RE_31 = {Σ, 2, {&RE_32, &RE_33}};
static PATTERN RE_35 = {σ, .s="?"};
static PATTERN RE_36 = {Shift, .t="?", .v=NULL};
static PATTERN RE_34 = {Σ, 2, {&RE_35, &RE_36}};
static PATTERN RE_27 = {Π, 3, {&RE_28, &RE_31, &RE_34}};
static PATTERN RE_37 = {Reduce, .x=2, .t="ς"};
static PATTERN RE_26 = {Σ, 2, {&RE_27, &RE_37}};
static PATTERN RE_38 = {ε};
static PATTERN RE_25 = {Π, 2, {&RE_26, &RE_38}};
static PATTERN RE_39 = {nInc};
static PATTERN RE_7 =  {Σ, 3, {&RE_8, &RE_25, &RE_39}};
static PATTERN RE_6 =  {ARBNO, 1, &RE_7};
static PATTERN RE_40 = {Reduce, .x=-1, .t="Σ"};
static PATTERN RE_41 = {nPop};
static PATTERN RE_4 =  {Σ, 4, {&RE_5, &RE_6, &RE_40, &RE_41}};
static PATTERN RE_42 = {nInc};
static PATTERN RE_45 = {σ, .s="|"};
static PATTERN RE_47 = {nPush};
static PATTERN RE_52 = {σ, .s="."};
static PATTERN RE_53 = {Shift, .t=".", .v=NULL};
static PATTERN RE_51 = {Σ, 2, {&RE_52, &RE_53}};
static PATTERN RE_55 = {σ, .s="\\"};
static PATTERN RE_57 = {ANY, .chars=".\\(|*+?)"};
static PATTERN RE_56 = {Δ, .s="tx", &RE_57};
static PATTERN RE_58 = {Shift, .t="σ", .v="tx"};
static PATTERN RE_54 = {Σ, 3, {&RE_55, &RE_56, &RE_58}};
static PATTERN RE_61 = {ANY, .chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"};
static PATTERN RE_60 = {Δ, .s="tx", &RE_61};
static PATTERN RE_62 = {Shift, .t="σ", .v="tx"};
static PATTERN RE_59 = {Σ, 2, {&RE_60, &RE_62}};
static PATTERN RE_64 = {σ, .s="("};
static PATTERN RE_65 = {ζ, .N="RE_Expression"};
static PATTERN RE_66 = {σ, .s=")"};
static PATTERN RE_63 = {Σ, 3, {&RE_64, &RE_65, &RE_66}};
static PATTERN RE_50 = {Π, 4, {&RE_51, &RE_54, &RE_59, &RE_63}};
static PATTERN RE_71 = {σ, .s="*"};
static PATTERN RE_72 = {Shift, .t="*", .v=NULL};
static PATTERN RE_70 = {Σ, 2, {&RE_71, &RE_72}};
static PATTERN RE_74 = {σ, .s="+"};
static PATTERN RE_75 = {Shift, .t="+", .v=NULL};
static PATTERN RE_73 = {Σ, 2, {&RE_74, &RE_75}};
static PATTERN RE_77 = {σ, .s="?"};
static PATTERN RE_78 = {Shift, .t="?", .v=NULL};
static PATTERN RE_76 = {Σ, 2, {&RE_77, &RE_78}};
static PATTERN RE_69 = {Π, 3, {&RE_70, &RE_73, &RE_76}};
static PATTERN RE_79 = {Reduce, .x=2, .t="ς"};
static PATTERN RE_68 = {Σ, 2, {&RE_69, &RE_79}};
static PATTERN RE_80 = {ε};
static PATTERN RE_67 = {Π, 2, {&RE_68, &RE_80}};
static PATTERN RE_81 = {nInc};
static PATTERN RE_49 = {Σ, 3, {&RE_50, &RE_67, &RE_81}};
static PATTERN RE_48 = {ARBNO, 1, &RE_49};
static PATTERN RE_82 = {Reduce, .x=-1, .t="Σ"};
static PATTERN RE_83 = {nPop};
static PATTERN RE_46 = {Σ, 4, {&RE_47, &RE_48, &RE_82, &RE_83}};
static PATTERN RE_84 = {nInc};
static PATTERN RE_44 = {Σ, 3, {&RE_45, &RE_46, &RE_84}};
static PATTERN RE_43 = {ARBNO, 1, &RE_44};
static PATTERN RE_85 = {Reduce, .x=-1, .t="Π"};
static PATTERN RE_86 = {nPop};
static PATTERN RE_2 =  {Σ, 6, {&RE_3, &RE_4, &RE_42, &RE_43, &RE_85, &RE_86}};
static PATTERN RE_87 = {Pop, .v="RE_tree"};
static PATTERN RE_88 = {RPOS, .n=0};
static PATTERN RE_0 =  {Σ, 4, {&RE_1, &RE_2, &RE_87, &RE_88}};

