static PATTERN RE_Quantifier_1 = {σ, .s="*"};
static PATTERN RE_Quantifier_2 = {σ, .s="+"};
static PATTERN RE_Quantifier_3 = {σ, .s="?"};
static PATTERN RE_Quantifier_0 = {Π, 3, {&RE_Quantifier_1, &RE_Quantifier_2, &RE_Quantifier_3}};
static PATTERN RE_Item_1 = {σ, .s="."};
static PATTERN RE_Item_3 = {σ, .s="\\"};
static PATTERN RE_Item_5 = {ANY, .chars=".\\(|*+?)"};
static PATTERN RE_Item_4 = {Δ, .s="tx", &RE_Item_5};
static PATTERN RE_Item_2 = {Σ, 2, {&RE_Item_3, &RE_Item_4}};
static PATTERN RE_Item_7 = {ANY, .chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"};
static PATTERN RE_Item_6 = {Δ, .s="tx", &RE_Item_7};
static PATTERN RE_Item_9 = {σ, .s="("};
static PATTERN RE_Item_10 = {ζ, .N="RE_Expression"};
static PATTERN RE_Item_11 = {σ, .s=")"};
static PATTERN RE_Item_8 = {Σ, 3, {&RE_Item_9, &RE_Item_10, &RE_Item_11}};
static PATTERN RE_Item_0 = {Π, 4, {&RE_Item_1, &RE_Item_2, &RE_Item_6, &RE_Item_8}};
static PATTERN RE_Factor_1 = {ζ, .N="RE_Item"};
static PATTERN RE_Factor_3 = {ζ, .N="RE_Quantifier"};
static PATTERN RE_Factor_4 = {ε};
static PATTERN RE_Factor_2 = {Π, 2, {&RE_Factor_3, &RE_Factor_4}};
static PATTERN RE_Factor_0 = {Σ, 2, {&RE_Factor_1, &RE_Factor_2}};
static PATTERN RE_Term_1 = {ζ, .N="RE_Factor"};
static PATTERN RE_Term_0 = {ARBNO, 1, &RE_Term_1};
static PATTERN RE_Expression_1 = {ζ, .N="RE_Term"};
static PATTERN RE_Expression_4 = {σ, .s="|"};
static PATTERN RE_Expression_5 = {ζ, .N="RE_Term"};
static PATTERN RE_Expression_3 = {Σ, 2, {&RE_Expression_4, &RE_Expression_5}};
static PATTERN RE_Expression_2 = {ARBNO, 1, &RE_Expression_3};
static PATTERN RE_Expression_0 = {Σ, 2, {&RE_Expression_1, &RE_Expression_2}};
static PATTERN RE_RegEx_1 = {POS, .n=0};
static PATTERN RE_RegEx_2 = {ζ, .N="RE_Expression"};
static PATTERN RE_RegEx_3 = {RPOS, .n=0};
static PATTERN RE_RegEx_0 = {Σ, 3, {&RE_RegEx_1, &RE_RegEx_2, &RE_RegEx_3}};

