static const PATTERN identifier_1 = {POS, .n=0};
static const PATTERN identifier_2 = {ANY, .chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"};
static const PATTERN identifier_5 = {SPAN, .chars=".0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz"};
static const PATTERN identifier_6 = {ε};
static const PATTERN identifier_4 = {Π, 2, {&identifier_5, &identifier_6}};
static const PATTERN identifier_3 = {FENCE, 1, &identifier_4};
static const PATTERN identifier_7 = {RPOS, .n=0};
static const PATTERN identifier_0 = {Σ, 4, {&identifier_1, &identifier_2, &identifier_3, &identifier_7}};

static const PATTERN real_number_1  = {POS, .n=0};
static const PATTERN real_number_5  = {SPAN, .chars="0123456789"};
static const PATTERN real_number_4  = {δ, .s="whole", &real_number_5};
static const PATTERN real_number_8  = {σ, .s="."};
static const PATTERN real_number_12 = {SPAN, .chars="0123456789"};
static const PATTERN real_number_13 = {ε};
static const PATTERN real_number_11 = {Π, 2, {&real_number_12, &real_number_13}};
static const PATTERN real_number_10 = {FENCE, 1, &real_number_11};
static const PATTERN real_number_9  = {δ, .s="fract", &real_number_10};
static const PATTERN real_number_7  = {Σ, 2, {&real_number_8, &real_number_9}};
static const PATTERN real_number_14 = {ε};
static const PATTERN real_number_6  = {Π, 2, {&real_number_7, &real_number_14}};
static const PATTERN real_number_16 = {σ, .s="E"};
static const PATTERN real_number_17 = {σ, .s="e"};
static const PATTERN real_number_15 = {Π, 2, {&real_number_16, &real_number_17}};
static const PATTERN real_number_19 = {σ, .s="+"};
static const PATTERN real_number_20 = {σ, .s="-"};
static const PATTERN real_number_21 = {ε};
static const PATTERN real_number_18 = {Π, 3, {&real_number_19, &real_number_20, &real_number_21}};
static const PATTERN real_number_23 = {SPAN, .chars="0123456789"};
static const PATTERN real_number_22 = {δ, .s="exp", &real_number_23};
static const PATTERN real_number_3  = {Σ, 5, {&real_number_4, &real_number_6, &real_number_15, &real_number_18, &real_number_22}};
static const PATTERN real_number_26 = {SPAN, .chars="0123456789"};
static const PATTERN real_number_25 = {δ, .s="whole", &real_number_26};
static const PATTERN real_number_27 = {σ, .s="."};
static const PATTERN real_number_31 = {SPAN, .chars="0123456789"};
static const PATTERN real_number_32 = {ε};
static const PATTERN real_number_30 = {Π, 2, {&real_number_31, &real_number_32}};
static const PATTERN real_number_29 = {FENCE, 1, &real_number_30};
static const PATTERN real_number_28 = {δ, .s="fract", &real_number_29};
static const PATTERN real_number_24 = {Σ, 3, {&real_number_25, &real_number_27, &real_number_28}};
static const PATTERN real_number_2  = {Π, 2, {&real_number_3, &real_number_24}};
static const PATTERN real_number_33 = {RPOS, .n=0};
static const PATTERN real_number_0  = {Σ, 3, {&real_number_1, &real_number_2, &real_number_33}};

