#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

#include "spipat.h"
#include "spipat_impl.h"

const char *image_strs[] = {
    [PC_Abort]	= "Abort",
    [PC_Alt]	= " | ",
    [PC_Any_CH]	= "Any",
    [PC_Any_CSP] = "Any",
    [PC_Any_VF]	= "Any",
    [PC_Any_VP]	= "Any",
    [PC_Arb_X]	= "Arb",
    [PC_Arbno_X] = "Arbno",
    [PC_Arbno_S] = "Arbno",
    [PC_Assign_Imm] = " * ",
    [PC_Assign_OnM] = " % ",
    [PC_Bal]	= "Bal",
    [PC_BreakX_CH] = "BreakX",
    [PC_BreakX_CSP] = "BreakX",
    [PC_BreakX_VF] = "BreakX",
    [PC_BreakX_VP] = "BreakX",
    [PC_Break_CH] = "Break",
    [PC_Break_CSP] = "Break",
    [PC_Break_VF] = "Break",
    [PC_Break_VP] = "Break",
    [PC_Call_Imm ] = " * ",
    [PC_Call_OnM ] = " % ",
    [PC_Dynamic_Func] = "Dynamic",
    [PC_Fail]	= "Fail",
    [PC_Fence]	= "Fence",
    [PC_Fence_X] = "Fence",
    [PC_Len_NF]	= "Len",
    [PC_Len_NP]	= "Len",
    [PC_Len_Nat] = "Len",
    [PC_NSpan_CH] = "NSpan",
    [PC_NSpan_CSP] = "NSpan",
    [PC_NSpan_VF] = "NSpan",
    [PC_NSpan_VP] = "NSpan",
    [PC_NotAny_CH] = "NotAny",
    [PC_NotAny_CSP] = "NotAny",
    [PC_NotAny_VF] = "NotAny",
    [PC_NotAny_VP] = "NotAny",
    [PC_Null]	= "\"\"",
    [PC_Pos_NF]	= "Pos",
    [PC_Pos_NP]	= "Pos",
    [PC_Pos_Nat] = "Pos",
    [PC_Pred_Func] = "Defer",
    [PC_RPos_NF] = "RPos",
    [PC_RPos_NP] = "RPos",
    [PC_RPos_Nat] = "RPos",
    [PC_RTab_NF] = "RTab",
    [PC_RTab_NP] = "RTab",
    [PC_RTab_Nat] = "RTab",
    [PC_Rem]	= "Rem",
    [PC_Rpat]	= "Defer",
    [PC_Setcur]	= "Setcur",
    [PC_Setcur_Func] = "Setcur",
    [PC_Span_CH] = "Span",
    [PC_Span_CSP] = "Span",
    [PC_Span_VF] = "Span",
    [PC_Span_VP] = "Span",
    [PC_Succeed] =  "Succeed",
    [PC_Tab_NF] = "Tab",
    [PC_Tab_NP] = "Tab",
    [PC_Tab_Nat] = "Tab",
};
