"Am I?" in POS(0) + V + σ(' ') + NS + σ('?') + RPOS(0)
"I am." in POS(0) + NS + σ(' ') + V + σ('.') + RPOS(0)
"Is it on?" in POS(0) + V + σ(' ') + ς('it') + σ(' ') + RA + σ('?') + RPOS(0)
"It is on." in POS(0) + ς('It') + σ(' ') + V + σ(' ') + RA + σ('.') + RPOS(0)
"Can she go?" in POS(0) + VN + σ(' ') + ς('she') + σ(' ') + VNA + σ('?') + RPOS(0)
"Do you run?" in POS(0) + VN + σ(' ') + ς('you') + σ(' ') + VN + σ('?') + RPOS(0)
"Is he here?" in POS(0) + V + σ(' ') + N + σ(' ') + NR + σ('?') + RPOS(0)
"Are we late?" in POS(0) + VN + σ(' ') + ς('we') + σ(' ') + RSA + σ('?') + RPOS(0)
"Can we talk?" in POS(0) + VN + σ(' ') + ς('we') + σ(' ') + VN + σ('?') + RPOS(0)
"Did she win?" in POS(0) + V + σ(' ') + ς('she') + σ(' ') + VN + σ('?') + RPOS(0)
"Did you eat?" in POS(0) + V + σ(' ') + ς('you') + σ(' ') + V + σ('?') + RPOS(0)
"Did you see?" in POS(0) + V + σ(' ') + ς('you') + σ(' ') + VN + σ('?') + RPOS(0)
"How are you?" in POS(0) + ς('How') + σ(' ') + VN + σ(' ') + ς('you') + σ('?') + RPOS(0)
"Should I go?" in POS(0) + ς('Should') + σ(' ') + NS + σ(' ') + VNA + σ('?') + RPOS(0)
"We saw them." in POS(0) + ς('We') + σ(' ') + VN + σ(' ') + ς('them') + σ('.') + RPOS(0)
"Where is he?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + N + σ('?') + RPOS(0)
"Who are you?" in POS(0) + ς('Who') + σ(' ') + VN + σ(' ') + ς('you') + σ('?') + RPOS(0)
"Are you sure?" in POS(0) + VN + σ(' ') + ς('you') + σ(' ') + RSA + σ('?') + RPOS(0)
"Did it break?" in POS(0) + V + σ(' ') + ς('it') + σ(' ') + VN + σ('?') + RPOS(0)
"Did she call?" in POS(0) + V + σ(' ') + ς('she') + σ(' ') + VN + σ('?') + RPOS(0)
"Did they win?" in POS(0) + V + σ(' ') + ς('they') + σ(' ') + VN + σ('?') + RPOS(0)
"Do birds fly?" in POS(0) + VN + σ(' ') + ς('birds') + σ(' ') + VNS + σ('?') + RPOS(0)
"Does it work?" in POS(0) + ς('Does') + σ(' ') + ς('it') + σ(' ') + VN + σ('?') + RPOS(0)
"Has she left?" in POS(0) + V + σ(' ') + ς('she') + σ(' ') + VNRA + σ('?') + RPOS(0)
"He loves her." in POS(0) + N + σ(' ') + ς('loves') + σ(' ') + ς('her') + σ('.') + RPOS(0)
"I like pizza." in POS(0) + NS + σ(' ') + VNSA + σ(' ') + N + σ('.') + RPOS(0)
"Is that true?" in POS(0) + V + σ(' ') + ς('that') + σ(' ') + RAVNS + σ('?') + RPOS(0)
"Is Tom ready?" in POS(0) + V + σ(' ') + N + σ(' ') + VNSA + σ('?') + RPOS(0)
"My dog barks." in POS(0) + ς('My') + σ(' ') + VN + σ(' ') + ς('barks') + σ('.') + RPOS(0)
"What is this?" in POS(0) + ς('What') + σ(' ') + V + σ(' ') + ς('this') + σ('?') + RPOS(0)
"Where is she?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + ς('she') + σ('?') + RPOS(0)
"Will he help?" in POS(0) + VN + σ(' ') + N + σ(' ') + VN + σ('?') + RPOS(0)
"Will he stay?" in POS(0) + VN + σ(' ') + N + σ(' ') + VN + σ('?') + RPOS(0)
"Will it rain?" in POS(0) + VN + σ(' ') + ς('it') + σ(' ') + VN + σ('?') + RPOS(0)
"Can dogs swim?" in POS(0) + VN + σ(' ') + ς('dogs') + σ(' ') + VN + σ('?') + RPOS(0)
"Did John call?" in POS(0) + V + σ(' ') + N + σ(' ') + VN + σ('?') + RPOS(0)
"Does time fly?" in POS(0) + ς('Does') + σ(' ') + VN + σ(' ') + VNS + σ('?') + RPOS(0)
"He sings well." in POS(0) + N + σ(' ') + ς('sings') + σ(' ') + VNRA + σ('.') + RPOS(0)
"He works hard." in POS(0) + N + σ(' ') + N + σ(' ') + RSA + σ('.') + RPOS(0)
"I heard music." in POS(0) + NS + σ(' ') + VS + σ(' ') + N + σ('.') + RPOS(0)
"Is the sun up?" in POS(0) + V + σ(' ') + ς('the') + σ(' ') + VN + σ(' ') + VRSA + σ('?') + RPOS(0)
"Is this yours?" in POS(0) + V + σ(' ') + ς('this') + σ(' ') + ς('yours') + σ('?') + RPOS(0)
"She runs fast." in POS(0) + ς('She') + σ(' ') + ς('runs') + σ(' ') + RAVNS + σ('.') + RPOS(0)
"They are here." in POS(0) + ς('They') + σ(' ') + VN + σ(' ') + NR + σ('.') + RPOS(0)
"Water is cold." in POS(0) + VN + σ(' ') + V + σ(' ') + NSA + σ('.') + RPOS(0)
"Why did he go?" in POS(0) + N + σ(' ') + V + σ(' ') + N + σ(' ') + VNA + σ('?') + RPOS(0)
"Birds fly high." in POS(0) + ς('Birds') + σ(' ') + VNS + σ(' ') + NRSA + σ('.') + RPOS(0)
"Can I help you?" in POS(0) + VN + σ(' ') + NS + σ(' ') + VN + σ(' ') + ς('you') + σ('?') + RPOS(0)
"Fish swim fast." in POS(0) + VN + σ(' ') + VN + σ(' ') + RAVNS + σ('.') + RPOS(0)
"Has it started?" in POS(0) + V + σ(' ') + ς('it') + σ(' ') + ς('started') + σ('?') + RPOS(0)
"The cat sleeps." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + ς('sleeps') + σ('.') + RPOS(0)
"The sun shines." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + ς('shines') + σ('.') + RPOS(0)
"Why is he late?" in POS(0) + N + σ(' ') + V + σ(' ') + N + σ(' ') + RSA + σ('?') + RPOS(0)
"Are they coming?" in POS(0) + VN + σ(' ') + ς('they') + σ(' ') + N + σ('?') + RPOS(0)
"Can you hear me?" in POS(0) + VN + σ(' ') + ς('you') + σ(' ') + V + σ(' ') + ς('me') + σ('?') + RPOS(0)
"Did she like it?" in POS(0) + V + σ(' ') + ς('she') + σ(' ') + VNSA + σ(' ') + ς('it') + σ('?') + RPOS(0)
"Dogs chase cats." in POS(0) + ς('Dogs') + σ(' ') + VN + σ(' ') + ς('cats') + σ('.') + RPOS(0)
"How do you know?" in POS(0) + ς('How') + σ(' ') + VN + σ(' ') + ς('you') + σ(' ') + VN + σ('?') + RPOS(0)
"Is this the way?" in POS(0) + V + σ(' ') + ς('this') + σ(' ') + ς('the') + σ(' ') + NR + σ('?') + RPOS(0)
"She feels happy." in POS(0) + ς('She') + σ(' ') + ς('feels') + σ(' ') + SA + σ('.') + RPOS(0)
"She found money." in POS(0) + ς('She') + σ(' ') + VNA + σ(' ') + N + σ('.') + RPOS(0)
"She reads books." in POS(0) + ς('She') + σ(' ') + ς('reads') + σ(' ') + ς('books') + σ('.') + RPOS(0)
"The clock ticks." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + ς('ticks') + σ('.') + RPOS(0)
"The door opened." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + SA + σ('.') + RPOS(0)
"What time is it?" in POS(0) + ς('What') + σ(' ') + VN + σ(' ') + V + σ(' ') + ς('it') + σ('?') + RPOS(0)
"Who took my pen?" in POS(0) + ς('Who') + σ(' ') + V + σ(' ') + ς('my') + σ(' ') + VN + σ('?') + RPOS(0)
"How does it work?" in POS(0) + ς('How') + σ(' ') + ς('does') + σ(' ') + ς('it') + σ(' ') + VN + σ('?') + RPOS(0)
"Rain falls today." in POS(0) + VN + σ(' ') + N + σ(' ') + NR + σ('.') + RPOS(0)
"What did she say?" in POS(0) + ς('What') + σ(' ') + V + σ(' ') + ς('she') + σ(' ') + VN + σ('?') + RPOS(0)
"When do we start?" in POS(0) + ς('When') + σ(' ') + VN + σ(' ') + ς('we') + σ(' ') + VN + σ('?') + RPOS(0)
"Where did you go?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + ς('you') + σ(' ') + VNA + σ('?') + RPOS(0)
"Where is my book?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + ς('my') + σ(' ') + VN + σ('?') + RPOS(0)
"Did they call you?" in POS(0) + V + σ(' ') + ς('they') + σ(' ') + VN + σ(' ') + ς('you') + σ('?') + RPOS(0)
"Have you seen him?" in POS(0) + VN + σ(' ') + ς('you') + σ(' ') + V + σ(' ') + ς('him') + σ('?') + RPOS(0)
"John studies hard." in POS(0) + N + σ(' ') + ς('studies') + σ(' ') + RSA + σ('.') + RPOS(0)
"We enjoyed dinner." in POS(0) + ς('We') + σ(' ') + ς('enjoyed') + σ(' ') + N + σ('.') + RPOS(0)
"When did it start?" in POS(0) + ς('When') + σ(' ') + V + σ(' ') + ς('it') + σ(' ') + VN + σ('?') + RPOS(0)
"Where are my keys?" in POS(0) + ς('Where') + σ(' ') + VN + σ(' ') + ς('my') + σ(' ') + ς('keys') + σ('?') + RPOS(0)
"Why do birds sing?" in POS(0) + N + σ(' ') + VN + σ(' ') + ς('birds') + σ(' ') + V + σ('?') + RPOS(0)
"How can I help you?" in POS(0) + ς('How') + σ(' ') + VN + σ(' ') + NS + σ(' ') + VN + σ(' ') + ς('you') + σ('?') + RPOS(0)
"Time flies quickly." in POS(0) + VN + σ(' ') + N + σ(' ') + R + σ('.') + RPOS(0)
"We visited Grandma." in POS(0) + ς('We') + σ(' ') + ς('visited') + σ(' ') + N + σ('.') + RPOS(0)
"Where is the hotel?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + ς('the') + σ(' ') + N + σ('?') + RPOS(0)
"Which way is right?" in POS(0) + ς('Which') + σ(' ') + NR + σ(' ') + V + σ(' ') + RAVNS + σ('?') + RPOS(0)
"Why did they leave?" in POS(0) + N + σ(' ') + V + σ(' ') + ς('they') + σ(' ') + VN + σ('?') + RPOS(0)
"Can you help me now?" in POS(0) + VN + σ(' ') + ς('you') + σ(' ') + VN + σ(' ') + ς('me') + σ(' ') + NR + σ('?') + RPOS(0)
"What made her upset?" in POS(0) + ς('What') + σ(' ') + VSA + σ(' ') + ς('her') + σ(' ') + VNS + σ('?') + RPOS(0)
"When will he arrive?" in POS(0) + ς('When') + σ(' ') + VN + σ(' ') + N + σ(' ') + V + σ('?') + RPOS(0)
"Where have you been?" in POS(0) + ς('Where') + σ(' ') + VN + σ(' ') + ς('you') + σ(' ') + V + σ('?') + RPOS(0)
"Where is your house?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + ς('your') + σ(' ') + VN + σ('?') + RPOS(0)
"Why is the sky blue?" in POS(0) + N + σ(' ') + V + σ(' ') + ς('the') + σ(' ') + VN + σ(' ') + VNS + σ('?') + RPOS(0)
"Are you feeling okay?" in POS(0) + VN + σ(' ') + ς('you') + σ(' ') + N + σ(' ') + VNRS + σ('?') + RPOS(0)
"Did you see the sign?" in POS(0) + V + σ(' ') + ς('you') + σ(' ') + VN + σ(' ') + ς('the') + σ(' ') + VN + σ('?') + RPOS(0)
"How did you break it?" in POS(0) + ς('How') + σ(' ') + V + σ(' ') + ς('you') + σ(' ') + VN + σ(' ') + ς('it') + σ('?') + RPOS(0)
"What did he tell you?" in POS(0) + ς('What') + σ(' ') + V + σ(' ') + N + σ(' ') + V + σ(' ') + ς('you') + σ('?') + RPOS(0)
"Where did he find it?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + N + σ(' ') + VN + σ(' ') + ς('it') + σ('?') + RPOS(0)
"Where did you put it?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + ς('you') + σ(' ') + VN + σ(' ') + ς('it') + σ('?') + RPOS(0)
"Which book is better?" in POS(0) + ς('Which') + σ(' ') + VN + σ(' ') + V + σ(' ') + RAVNS + σ('?') + RPOS(0)
"Why did she run away?" in POS(0) + N + σ(' ') + V + σ(' ') + ς('she') + σ(' ') + VN + σ(' ') + RSA + σ('?') + RPOS(0)
"Did they arrive early?" in POS(0) + V + σ(' ') + ς('they') + σ(' ') + V + σ(' ') + RSA + σ('?') + RPOS(0)
"Did you lock the door?" in POS(0) + V + σ(' ') + ς('you') + σ(' ') + VN + σ(' ') + ς('the') + σ(' ') + N + σ('?') + RPOS(0)
"Has the train arrived?" in POS(0) + V + σ(' ') + ς('the') + σ(' ') + VN + σ(' ') + ς('arrived') + σ('?') + RPOS(0)
"Have you finished yet?" in POS(0) + VN + σ(' ') + ς('you') + σ(' ') + SA + σ(' ') + R + σ('?') + RPOS(0)
"How much does it cost?" in POS(0) + ς('How') + σ(' ') + NR + σ(' ') + ς('does') + σ(' ') + ς('it') + σ(' ') + VN + σ('?') + RPOS(0)
"I saw a shooting star." in POS(0) + NS + σ(' ') + VN + σ(' ') + N + σ(' ') + N + σ(' ') + VN + σ('.') + RPOS(0)
"The baby cried loudly." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + V + σ(' ') + R + σ('.') + RPOS(0)
"They finished quickly." in POS(0) + ς('They') + σ(' ') + SA + σ(' ') + R + σ('.') + RPOS(0)
"Tom opened the window." in POS(0) + N + σ(' ') + SA + σ(' ') + ς('the') + σ(' ') + N + σ('.') + RPOS(0)
"Which road leads home?" in POS(0) + ς('Which') + σ(' ') + N + σ(' ') + ς('leads') + σ(' ') + VNRA + σ('?') + RPOS(0)
"How far is the airport?" in POS(0) + ς('How') + σ(' ') + RSA + σ(' ') + V + σ(' ') + ς('the') + σ(' ') + N + σ('?') + RPOS(0)
"How many apples remain?" in POS(0) + ς('How') + σ(' ') + A + σ(' ') + ς('apples') + σ(' ') + V + σ('?') + RPOS(0)
"I found my lost wallet." in POS(0) + NS + σ(' ') + VNA + σ(' ') + ς('my') + σ(' ') + VNSA + σ(' ') + N + σ('.') + RPOS(0)
"The train arrived late." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + ς('arrived') + σ(' ') + RSA + σ('.') + RPOS(0)
"When is the next train?" in POS(0) + ς('When') + σ(' ') + V + σ(' ') + ς('the') + σ(' ') + RS + σ(' ') + VN + σ('?') + RPOS(0)
"Who left the door open?" in POS(0) + ς('Who') + σ(' ') + VNRA + σ(' ') + ς('the') + σ(' ') + N + σ(' ') + VNSA + σ('?') + RPOS(0)
"Why are you still here?" in POS(0) + N + σ(' ') + VN + σ(' ') + ς('you') + σ(' ') + RAVNS + σ(' ') + NR + σ('?') + RPOS(0)
"Did she buy the tickets?" in POS(0) + V + σ(' ') + ς('she') + σ(' ') + VN + σ(' ') + ς('the') + σ(' ') + ς('tickets') + σ('?') + RPOS(0)
"Flowers bloom in spring." in POS(0) + ς('Flowers') + σ(' ') + VN + σ(' ') + NRS + σ(' ') + VN + σ('.') + RPOS(0)
"What time does it start?" in POS(0) + ς('What') + σ(' ') + VN + σ(' ') + ς('does') + σ(' ') + ς('it') + σ(' ') + VN + σ('?') + RPOS(0)
"Who is knocking outside?" in POS(0) + ς('Who') + σ(' ') + V + σ(' ') + N + σ(' ') + NRSA + σ('?') + RPOS(0)
"Can I borrow your laptop?" in POS(0) + VN + σ(' ') + NS + σ(' ') + V + σ(' ') + ς('your') + σ(' ') + N + σ('?') + RPOS(0)
"His idea changed my mind." in POS(0) + ς('His') + σ(' ') + N + σ(' ') + SA + σ(' ') + ς('my') + σ(' ') + VN + σ('.') + RPOS(0)
"What happened last night?" in POS(0) + ς('What') + σ(' ') + ς('happened') + σ(' ') + RAVNS + σ(' ') + N + σ('?') + RPOS(0)
"When does the store open?" in POS(0) + ς('When') + σ(' ') + ς('does') + σ(' ') + ς('the') + σ(' ') + VN + σ(' ') + VNSA + σ('?') + RPOS(0)
"Who borrowed my notebook?" in POS(0) + ς('Who') + σ(' ') + ς('borrowed') + σ(' ') + ς('my') + σ(' ') + N + σ('?') + RPOS(0)
"Have you been here before?" in POS(0) + VN + σ(' ') + ς('you') + σ(' ') + V + σ(' ') + NR + σ(' ') + R + σ('?') + RPOS(0)
"She made a delicious cake." in POS(0) + ς('She') + σ(' ') + VSA + σ(' ') + N + σ(' ') + S + σ(' ') + VN + σ('.') + RPOS(0)
"She painted the old house." in POS(0) + ς('She') + σ(' ') + SA + σ(' ') + ς('the') + σ(' ') + NSA + σ(' ') + VN + σ('.') + RPOS(0)
"We walked along the river." in POS(0) + ς('We') + σ(' ') + ς('walked') + σ(' ') + R + σ(' ') + ς('the') + σ(' ') + N + σ('.') + RPOS(0)
"Where did you last see it?" in POS(0) + ς('Where') + σ(' ') + V + σ(' ') + ς('you') + σ(' ') + RAVNS + σ(' ') + VN + σ(' ') + ς('it') + σ('?') + RPOS(0)
"Which color do you prefer?" in POS(0) + ς('Which') + σ(' ') + VNA + σ(' ') + VN + σ(' ') + ς('you') + σ(' ') + V + σ('?') + RPOS(0)
"He suddenly stopped running." in POS(0) + N + σ(' ') + R + σ(' ') + VS + σ(' ') + VN + σ('.') + RPOS(0)
"John fixed the broken chair." in POS(0) + N + σ(' ') + SA + σ(' ') + ς('the') + σ(' ') + VSA + σ(' ') + VN + σ('.') + RPOS(0)
"My friend sings beautifully." in POS(0) + ς('My') + σ(' ') + N + σ(' ') + ς('sings') + σ(' ') + R + σ('.') + RPOS(0)
"She quickly closed the book." in POS(0) + ς('She') + σ(' ') + R + σ(' ') + SA + σ(' ') + ς('the') + σ(' ') + VN + σ('.') + RPOS(0)
"The new restaurant is great." in POS(0) + ς('The') + σ(' ') + RSA + σ(' ') + N + σ(' ') + V + σ(' ') + NS + σ('.') + RPOS(0)
"They will visit us tomorrow." in POS(0) + ς('They') + σ(' ') + VN + σ(' ') + VN + σ(' ') + ς('us') + σ(' ') + NR + σ('.') + RPOS(0)
"What is your favorite movie?" in POS(0) + ς('What') + σ(' ') + V + σ(' ') + ς('your') + σ(' ') + VNS + σ(' ') + N + σ('?') + RPOS(0)
"Who will attend the meeting?" in POS(0) + ς('Who') + σ(' ') + VN + σ(' ') + V + σ(' ') + ς('the') + σ(' ') + N + σ('?') + RPOS(0)
"Did you forget your password?" in POS(0) + V + σ(' ') + ς('you') + σ(' ') + V + σ(' ') + ς('your') + σ(' ') + N + σ('?') + RPOS(0)
"Our teacher gave us homework." in POS(0) + ς('Our') + σ(' ') + N + σ(' ') + V + σ(' ') + ς('us') + σ(' ') + N + σ('.') + RPOS(0)
"Why was he acting so strange?" in POS(0) + N + σ(' ') + V + σ(' ') + N + σ(' ') + N + σ(' ') + NR + σ(' ') + SA + σ('?') + RPOS(0)
"The little boy smiled happily." in POS(0) + ς('The') + σ(' ') + NRSA + σ(' ') + N + σ(' ') + ς('smiled') + σ(' ') + R + σ('.') + RPOS(0)
"We finished the project early." in POS(0) + ς('We') + σ(' ') + SA + σ(' ') + ς('the') + σ(' ') + VN + σ(' ') + RSA + σ('.') + RPOS(0)
"Where should we meet tomorrow?" in POS(0) + ς('Where') + σ(' ') + ς('should') + σ(' ') + ς('we') + σ(' ') + VNS + σ(' ') + NR + σ('?') + RPOS(0)
"How did they solve the problem?" in POS(0) + ς('How') + σ(' ') + V + σ(' ') + ς('they') + σ(' ') + V + σ(' ') + ς('the') + σ(' ') + N + σ('?') + RPOS(0)
"A strong wind blew through town." in POS(0) + N + σ(' ') + SA + σ(' ') + VN + σ(' ') + V + σ(' ') + RS + σ(' ') + N + σ('.') + RPOS(0)
"The children played in the park." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + A + σ(' ') + NRS + σ(' ') + ς('the') + σ(' ') + VN + σ('.') + RPOS(0)
"We bought a brand-new car today." in POS(0) + ς('We') + σ(' ') + V + σ(' ') + N + σ(' ') + VN + σ('-') + RSA + σ(' ') + N + σ(' ') + NR + σ('.') + RPOS(0)
"She quickly wrote a short letter." in POS(0) + ς('She') + σ(' ') + R + σ(' ') + V + σ(' ') + N + σ(' ') + RAVNS + σ(' ') + VN + σ('.') + RPOS(0)
"The birds chirped in the morning." in POS(0) + ς('The') + σ(' ') + ς('birds') + σ(' ') + ς('chirped') + σ(' ') + NRS + σ(' ') + ς('the') + σ(' ') + N + σ('.') + RPOS(0)
"The storm knocked down the trees." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + ς('knocked') + σ(' ') + RAVNS + σ(' ') + ς('the') + σ(' ') + ς('trees') + σ('.') + RPOS(0)
"She beautifully played the violin." in POS(0) + ς('She') + σ(' ') + R + σ(' ') + A + σ(' ') + ς('the') + σ(' ') + N + σ('.') + RPOS(0)
"The dog eagerly fetched the stick." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + R + σ(' ') + ς('fetched') + σ(' ') + ς('the') + σ(' ') + VN + σ('.') + RPOS(0)
"The firemen rescued a trapped dog." in POS(0) + ς('The') + σ(' ') + ς('firemen') + σ(' ') + S + σ(' ') + N + σ(' ') + VS + σ(' ') + VN + σ('.') + RPOS(0)
"The students listened attentively." in POS(0) + ς('The') + σ(' ') + ς('students') + σ(' ') + ς('listened') + σ(' ') + R + σ('.') + RPOS(0)
"We enjoyed our vacation in Hawaii." in POS(0) + ς('We') + σ(' ') + ς('enjoyed') + σ(' ') + ς('our') + σ(' ') + VN + σ(' ') + NRS + σ(' ') + ς('Hawaii') + σ('.') + RPOS(0)
"We prepared a big meal for dinner." in POS(0) + ς('We') + σ(' ') + SA + σ(' ') + N + σ(' ') + RSA + σ(' ') + N + σ(' ') + ς('for') + σ(' ') + N + σ('.') + RPOS(0)
"He carefully examined the old book." in POS(0) + N + σ(' ') + R + σ(' ') + ς('examined') + σ(' ') + ς('the') + σ(' ') + NSA + σ(' ') + VN + σ('.') + RPOS(0)
"She carefully arranged the flowers." in POS(0) + ς('She') + σ(' ') + R + σ(' ') + SA + σ(' ') + ς('the') + σ(' ') + ς('flowers') + σ('.') + RPOS(0)
"The phone suddenly stopped working." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + R + σ(' ') + VS + σ(' ') + NS + σ('.') + RPOS(0)
"Tom accidentally spilled his drink." in POS(0) + N + σ(' ') + R + σ(' ') + ς('spilled') + σ(' ') + ς('his') + σ(' ') + VN + σ('.') + RPOS(0)
"Which restaurant has the best food?" in POS(0) + ς('Which') + σ(' ') + N + σ(' ') + V + σ(' ') + ς('the') + σ(' ') + RAVNS + σ(' ') + N + σ('?') + RPOS(0)
"The airplane landed safely at night." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + A + σ(' ') + R + σ(' ') + N + σ(' ') + N + σ('.') + RPOS(0)
"They discovered an ancient artifact." in POS(0) + ς('They') + σ(' ') + S + σ(' ') + ς('an') + σ(' ') + NS + σ(' ') + N + σ('.') + RPOS(0)
"The old castle stood tall and strong." in POS(0) + ς('The') + σ(' ') + NSA + σ(' ') + VN + σ(' ') + V + σ(' ') + NSA + σ(' ') + ς('and') + σ(' ') + SA + σ('.') + RPOS(0)
"He carefully carried the fragile vase." in POS(0) + N + σ(' ') + R + σ(' ') + V + σ(' ') + ς('the') + σ(' ') + S + σ(' ') + N + σ('.') + RPOS(0)
"She decorated the house for the party." in POS(0) + ς('She') + σ(' ') + A + σ(' ') + ς('the') + σ(' ') + VN + σ(' ') + ς('for') + σ(' ') + ς('the') + σ(' ') + VN + σ('.') + RPOS(0)
"She designed an elegant wedding dress." in POS(0) + ς('She') + σ(' ') + A + σ(' ') + ς('an') + σ(' ') + SA + σ(' ') + VN + σ(' ') + VNS + σ('.') + RPOS(0)
"The beautiful flowers smell wonderful." in POS(0) + ς('The') + σ(' ') + SA + σ(' ') + ς('flowers') + σ(' ') + VN + σ(' ') + S + σ('.') + RPOS(0)
"The curious cat climbed the bookshelf." in POS(0) + ς('The') + σ(' ') + SA + σ(' ') + VN + σ(' ') + ς('climbed') + σ(' ') + ς('the') + σ(' ') + N + σ('.') + RPOS(0)
"The scientist discovered a new planet." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + S + σ(' ') + N + σ(' ') + RSA + σ(' ') + N + σ('.') + RPOS(0)
"We listened to the music with delight." in POS(0) + ς('We') + σ(' ') + ς('listened') + σ(' ') + ς('to') + σ(' ') + ς('the') + σ(' ') + N + σ(' ') + ς('with') + σ(' ') + VN + σ('.') + RPOS(0)
"Our teacher explained the math problem." in POS(0) + ς('Our') + σ(' ') + N + σ(' ') + ς('explained') + σ(' ') + ς('the') + σ(' ') + N + σ(' ') + N + σ('.') + RPOS(0)
"They finally reached their destination." in POS(0) + ς('They') + σ(' ') + R + σ(' ') + ς('reached') + σ(' ') + ς('their') + σ(' ') + N + σ('.') + RPOS(0)
"The artist painted a breathtaking sunset." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + SA + σ(' ') + N + σ(' ') + S + σ(' ') + NS + σ('.') + RPOS(0)
"The train departed from the busy station." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + NS + σ(' ') + ς('from') + σ(' ') + ς('the') + σ(' ') + VSA + σ(' ') + VN + σ('.') + RPOS(0)
"The young musician composed a new melody." in POS(0) + ς('The') + σ(' ') + NSA + σ(' ') + N + σ(' ') + A + σ(' ') + N + σ(' ') + RSA + σ(' ') + N + σ('.') + RPOS(0)
"The little girl eagerly opened her present." in POS(0) + ς('The') + σ(' ') + NRSA + σ(' ') + N + σ(' ') + R + σ(' ') + SA + σ(' ') + ς('her') + σ(' ') + VNA + σ('.') + RPOS(0)
"The strong wind knocked down several trees." in POS(0) + ς('The') + σ(' ') + SA + σ(' ') + VN + σ(' ') + ς('knocked') + σ(' ') + RAVNS + σ(' ') + ς('several') + σ(' ') + ς('trees') + σ('.') + RPOS(0)
"The birds gracefully soared through the sky." in POS(0) + ς('The') + σ(' ') + ς('birds') + σ(' ') + R + σ(' ') + ς('soared') + σ(' ') + RS + σ(' ') + ς('the') + σ(' ') + VN + σ('.') + RPOS(0)
"The sun slowly disappeared behind mountains." in POS(0) + ς('The') + σ(' ') + VN + σ(' ') + R + σ(' ') + ς('disappeared') + σ(' ') + NR + σ(' ') + ς('mountains') + σ('.') + RPOS(0)
"Our grandparents told us fascinating stories." in POS(0) + ς('Our') + σ(' ') + ς('grandparents') + σ(' ') + V + σ(' ') + ς('us') + σ(' ') + S + σ(' ') + ς('stories') + σ('.') + RPOS(0)
"She quickly packed her suitcase for vacation." in POS(0) + ς('She') + σ(' ') + R + σ(' ') + S + σ(' ') + ς('her') + σ(' ') + N + σ(' ') + ς('for') + σ(' ') + VN + σ('.') + RPOS(0)
"We built a sturdy wooden treehouse last summer." in POS(0) + ς('We') + σ(' ') + VS + σ(' ') + N + σ(' ') + SA + σ(' ') + S + σ(' ') + ς('treehouse') + σ(' ') + RAVNS + σ(' ') + VN + σ('.') + RPOS(0)
"We watched the fireworks explode over the lake." in POS(0) + ς('We') + σ(' ') + ς('watched') + σ(' ') + ς('the') + σ(' ') + ς('fireworks') + σ(' ') + V + σ(' ') + NR + σ(' ') + ς('the') + σ(' ') + N + σ('.') + RPOS(0)
"She gracefully danced across the grand ballroom." in POS(0) + ς('She') + σ(' ') + R + σ(' ') + ς('danced') + σ(' ') + R + σ(' ') + ς('the') + σ(' ') + NS + σ(' ') + N + σ('.') + RPOS(0)
"The chef prepared an exquisite five-course meal." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + SA + σ(' ') + ς('an') + σ(' ') + S + σ(' ') + NS + σ('-') + VNR + σ(' ') + N + σ('.') + RPOS(0)
"The experienced guide led us through the forest." in POS(0) + ς('The') + σ(' ') + A + σ(' ') + VN + σ(' ') + V + σ(' ') + ς('us') + σ(' ') + RS + σ(' ') + ς('the') + σ(' ') + VN + σ('.') + RPOS(0)
"The scientist conducted an important experiment." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + ς('conducted') + σ(' ') + ς('an') + σ(' ') + SA + σ(' ') + VN + σ('.') + RPOS(0)
"The detective solved the mysterious case quickly." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + A + σ(' ') + ς('the') + σ(' ') + S + σ(' ') + VN + σ(' ') + R + σ('.') + RPOS(0)
"The audience applauded the incredible performance." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + ς('applauded') + σ(' ') + ς('the') + σ(' ') + A + σ(' ') + N + σ('.') + RPOS(0)
"The little boy excitedly opened his birthday gift." in POS(0) + ς('The') + σ(' ') + NRSA + σ(' ') + N + σ(' ') + R + σ(' ') + SA + σ(' ') + ς('his') + σ(' ') + N + σ(' ') + VN + σ('.') + RPOS(0)
"The brave firefighter rescued a kitten from danger." in POS(0) + ς('The') + σ(' ') + VNSA + σ(' ') + N + σ(' ') + S + σ(' ') + N + σ(' ') + VN + σ(' ') + ς('from') + σ(' ') + N + σ('.') + RPOS(0)
"The championship team celebrated their big victory." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + VN + σ(' ') + S + σ(' ') + ς('their') + σ(' ') + RSA + σ(' ') + N + σ('.') + RPOS(0)
"The enthusiastic teacher inspired all her students." in POS(0) + ς('The') + σ(' ') + A + σ(' ') + N + σ(' ') + S + σ(' ') + RS + σ(' ') + ς('her') + σ(' ') + ς('students') + σ('.') + RPOS(0)
"The astronomer discovered a distant, unknown galaxy." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + S + σ(' ') + N + σ(' ') + SA + σ(',') + σ(' ') + NSA + σ(' ') + N + σ('.') + RPOS(0)
"The scientist developed a groundbreaking new theory." in POS(0) + ς('The') + σ(' ') + N + σ(' ') + SA + σ(' ') + N + σ(' ') + NS + σ(' ') + RSA + σ(' ') + N + σ('.') + RPOS(0)
"She meticulously crafted a beautiful, handmade quilt." in POS(0) + ς('She') + σ(' ') + R + σ(' ') + ς('crafted') + σ(' ') + N + σ(' ') + SA + σ(',') + σ(' ') + A + σ(' ') + VN + σ('.') + RPOS(0)
"The determined athlete trained rigorously for the marathon." in POS(0) + ς('The') + σ(' ') + SA + σ(' ') + N + σ(' ') + A + σ(' ') + R + σ(' ') + ς('for') + σ(' ') + ς('the') + σ(' ') + N + σ('.') + RPOS(0)
